openapi: 3.0.0
info:
  title: cie-bff
  version: '1.0'
  description: API definition for CIE bff
  contact:
    email: cyril.baurand@ch.glory-global.com
    name: Cyril Baurand
servers:
  - url: 'http://localhost:3000'
    description: local machine for debug
paths:
  /login:
    get:
      summary: get login URL
      responses:
        '200':
          $ref: '#/components/responses/GetLogin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-login
      description: Get App ID login screen URL.
      parameters:
        - $ref: '#/components/parameters/connect.sid'
        - schema:
            type: string
            minLength: 1
          in: query
          name: redirectUrl
          description: URL to redirect after authentication
      tags:
        - User Auth
    parameters: []
  /token:
    get:
      summary: get token's
      tags:
        - User Auth
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-token
      description: 'Get access token, refresh token.'
      parameters:
        - $ref: '#/components/parameters/connect.sid'
        - $ref: '#/components/parameters/applicationId'
        - $ref: '#/components/parameters/redirectUrl'
        - $ref: '#/components/parameters/code'
  /userInfo:
    get:
      summary: get a user info
      tags:
        - User Auth
      responses:
        '200':
          $ref: '#/components/responses/GetUserInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-userInfo
      description: Get a user information.
      parameters:
        - $ref: '#/components/parameters/connect.sid'
        - $ref: '#/components/parameters/applicationId'
  /logout:
    post:
      summary: logout Application
      operationId: post-logout
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      description: Log out of the application.
      parameters:
        - $ref: '#/components/parameters/connect.sid'
      tags:
        - User Auth
  /areas:
    get:
      summary: get areas info
      responses:
        '200':
          $ref: '#/components/responses/GetAreas'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-areas
      description: Get areas information
      tags:
        - Area
      parameters:
        - $ref: '#/components/parameters/connect.sid'
  /stores:
    get:
      summary: get stores info
      tags:
        - Store
      responses:
        '200':
          $ref: '#/components/responses/GetStores'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-stores
      description: Get stores information
      parameters:
        - $ref: '#/components/parameters/connect.sid'
        - $ref: '#/components/parameters/areaName'
  /cis/roles:
    get:
      summary: get cis roles
      responses:
        '200':
          $ref: '#/components/responses/GetCisRoles'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-cis-roles
      description: Get cis roles
      parameters:
        - $ref: '#/components/parameters/connect.sid'
      tags:
        - CIS Role
    parameters: []
  /cis/users:
    get:
      summary: get available cis users
      responses:
        '200':
          $ref: '#/components/responses/GetCisUsersList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-cis-user
      description: Get cis user list
      parameters:
        - $ref: '#/components/parameters/connect.sid'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: string
            minLength: 1
          in: query
          name: text
          description: 'Free text to seach fields (userId, userName)'
        - $ref: '#/components/parameters/areaName'
        - $ref: '#/components/parameters/storeName'
      tags:
        - CIS User
    parameters: []
  '/cis/users/{userId}':
    get:
      summary: get a cis user info
      responses:
        '200':
          $ref: '#/components/responses/GetCisUsers'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      operationId: get-cis-users-userid
      parameters:
        - $ref: '#/components/parameters/connect.sid'
      description: get a cis user information
      tags:
        - CIS User
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      summary: creates new cis users
      operationId: post-cis-users-userId
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCisUsers'
              examples:
                example-1:
                  value:
                    userName: tom
                    status: Active
                    roles:
                      - roleName: Manager
                    stores:
                      - storeName: West Store
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      parameters:
        - $ref: '#/components/parameters/connect.sid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCisUsers'
            examples:
              example-1:
                value:
                  userName: tom
                  status: Active
                  roles:
                    - roleName: Manager
                  stores:
                    - storeName: West Store
      tags:
        - CIS User
      description: creates new cis users
    put:
      summary: update cis users
      operationId: put-cis-users-userId
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutCisUsers'
              examples:
                example-1:
                  value:
                    newUserId: cieuser004
                    userName: tom
                    status: Active
                    roles:
                      - roleName: Manager
                    stores:
                      - storeName: West Stores
                    passwordChangeFlag: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      description: update cis users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutCisUsers'
            examples:
              example-1:
                value:
                  newUserId: cieuser004
                  userName: tom
                  status: Active
                  roles:
                    - roleName: Manager
                  stores:
                    - storeName: West Stores
                  passwordChangeFlag: true
      tags:
        - CIS User
    delete:
      summary: delete cis users
      operationId: delete-cis-users-userId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      tags:
        - CIS User
      description: delete cis users
  '/cis/users/{userId}/restore':
    parameters:
      - $ref: '#/components/parameters/userId'
    put:
      summary: restore cis users
      operationId: put-cis-users-userId-delete
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/UnexpectedError'
      tags:
        - CIS User
      description: restore cis users
components:
  schemas:
    PostCisUsers:
      title: PostCisUsers
      type: object
      description: 'Model of POST /cisUsers/{userId}'
      x-examples:
        example-1:
          userName: tom
          status: Active
          roles:
            - roleName: Manager
          stores:
            - storeName: West Store
      properties:
        userName:
          type: string
          description: user name
          maxLength: 40
          pattern: '^[a-z0-9!@#\\$%&\\*\\(\\)~\\?=;:,\\.\\{\\}\\+\\-`\\|\\/<>]+$'
          minLength: 1
        status:
          type: string
          description: status
          enum:
            - Active
            - Inactive
        roles:
          type: array
          items:
            type: object
            properties:
              roleName:
                type: string
                description: role name
                minLength: 1
            required:
              - roleName
        stores:
          type: array
          items:
            type: object
            properties:
              storeName:
                type: string
                description: store name
                minLength: 1
            required:
              - storeName
      required:
        - userName
        - status
        - roles
        - stores
    PutCisUsers:
      title: PutCisUsers
      type: object
      description: 'Model of PUT /cis/users/{userId}'
      x-examples:
        example-1:
          newUserId: cieuser004
          userName: tom
          status: Active
          roles:
            - roleName: Manager
          stores:
            - storeName: West Store
          passwordChangeFlag: true
      properties:
        newUserId:
          type: string
          description: new user id
          maxLength: 20
          pattern: '^[a-z0-9]+$'
          minLength: 1
        userName:
          type: string
          description: user name
          maxLength: 40
          pattern: '^[a-z0-9!@#\\$%&\\*\\(\\)~\\?=;:,\\.\\{\\}\\+\\-`\\|\\/<>]+$'
          minLength: 1
        status:
          type: string
          description: status
          enum:
            - Active
            - Inactive
        roles:
          type: array
          items:
            type: object
            properties:
              roleName:
                type: string
                description: role name
                minLength: 1
            required:
              - roleName
        stores:
          type: array
          items:
            type: object
            properties:
              storeName:
                type: string
                description: store name
                minLength: 1
            required:
              - storeName
        passwordChangeFlag:
          type: boolean
          description: password change flag(true is checked)
      required:
        - newUserId
        - userName
        - status
        - roles
        - stores
  securitySchemes: {}
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 400
                message: Invalid Request Body
            example-2:
              value:
                code: 400
                message: Invalid Request Path Params
            example-3:
              value:
                code: 400
                message: Invalid Request Params
    Unauthorised:
      description: Unauthorised
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 401
                message: Unauthorized
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 403
                message: Forbidden
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 404
                message: Not Found
    ConflictError:
      description: Conflict Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 409
                message: Conflict Error
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
          examples:
            example-1:
              value:
                code: 500
                message: Unexpected Error
    GetLogin:
      description: 'Response of Get /login '
      content:
        application/json:
          schema:
            type: object
            properties:
              authUrl:
                type: string
                description: URL for the login screen
            required:
              - authUrl
          examples:
            example-1:
              value:
                authUrl: 'https://eu-de.appid.cloud.ibm.com/oauth/v4/325711e7-86e8-4bb0-bf09-f2547agea8ea/authorization?client_id=e5279777-fc3d-45b9-b6c7-7355e36d5409&response_type=code&redirect_uri=http://localhost:3000/token_callback&scope=appid_default&language=eu&state=EzRsK3lYg41BjtQ4-TYd8zX4H2g%3D'
        application/xml:
          schema:
            type: object
            properties: {}
      headers: {}
    GetUserInfo:
      description: Response of Get /userInfo
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                description: IBM Cloud Directory User ID
              email:
                type: string
                description: email address
              displayName:
                type: string
                description: IBM Cloud Directory User Name Display String
              language:
                type: string
                description: settings language
              firstLoginDate:
                type: string
                description: First login date time
            required:
              - userId
              - email
              - displayName
          examples:
            example-1:
              value:
                userId: a638bfa0-099d-41c3-a840-fa3e9897953a
                email: sample@test.com
                displayName: User Name
                firstLoginDate: '2020-12-01T01:02:03+09:00'
    GetAreas:
      description: |-
        Response of Get /areas
        If the number of results obtained is zero, status returns 200.
      content:
        application/json:
          schema:
            type: object
            properties:
              totalCount:
                type: number
                description: total count
              items:
                type: array
                items:
                  type: object
                  properties:
                    areaName:
                      type: string
                      description: area name
                  required:
                    - areaName
            required:
              - totalCount
              - items
          examples:
            example-1:
              value:
                totalCount: 2
                items:
                  - areaName: East Area
                  - areaName: West Area
            example-2:
              value:
                totalCount: 0
                items: []
    GetStores:
      description: |-
        Response of Get /stores
        If the number of results obtained is zero, status returns 200.
        If the store does not belong to an area, make the area No Area.
        Check the samples.
      content:
        application/json:
          schema:
            type: object
            properties:
              totalCount:
                type: number
                description: total count
              items:
                type: array
                items:
                  type: object
                  properties:
                    areaName:
                      type: string
                      description: area name
                    stores:
                      type: array
                      items:
                        type: object
                        properties:
                          storeName:
                            type: string
                            description: store name
                        required:
                          - storeName
                  required:
                    - areaName
            required:
              - totalCount
              - items
          examples:
            example-1:
              value:
                totalCount: 2
                items:
                  - areaName: West Area
                    stores:
                      - storeName: West Store
                  - areaName: No Area
                    stores:
                      - storeName: Store
            example-2:
              value:
                totalCount: 0
                items: []
    GetCisRoles:
      description: |-
        Response of Get /cis/roles
        If the number of results obtained is zero, status returns 200.
      content:
        application/json:
          schema:
            type: object
            properties:
              totalCount:
                type: number
                description: total count
              items:
                type: array
                items:
                  type: object
                  properties:
                    roleName:
                      type: string
                      description: role name
                  required:
                    - roleName
            required:
              - totalCount
              - items
          examples:
            example-1:
              value:
                totalCount: 5
                items:
                  - roleName: Manager
                  - roleName: CIT
                  - roleName: Service
                  - roleName: Cashier
                  - roleName: Other
            example-2:
              value:
                totalCount: 0
                items: []
    GetCisUsersList:
      description: |-
        Response of Get /cis/users
        If the number of results obtained is zero, status returns 200.
      content:
        application/json:
          schema:
            type: object
            properties:
              totalCount:
                type: number
                description: total count
              items:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                      description: user ID(User ID of CIS user)
                    userName:
                      type: string
                      description: user name
                    status:
                      type: string
                      description: status
                      enum:
                        - Active
                        - Inactive
                    deleteFlag:
                      type: boolean
                      description: delete flag(true is deleted)
                    areas:
                      type: array
                      items:
                        type: object
                        properties:
                          areaName:
                            type: string
                            description: area name
                        required:
                          - areaName
                    stores:
                      type: array
                      items:
                        type: object
                        properties:
                          storeName:
                            type: string
                            description: store name
                        required:
                          - storeName
                    totalCount:
                      type: number
                      description: total count(without offset and limit)
                  required:
                    - userId
                    - userName
                    - status
                    - deleteFlag
                    - areas
                    - stores
                    - totalCount
            required:
              - totalCount
              - items
          examples:
            example-1:
              value:
                totalCount: 2
                items:
                  - userId: cisuser1
                    userName: cis-user-1-1
                    status: Active
                    deleteFlag: false
                    areas:
                      - areaName: East Area
                    stores:
                      - storeName: Himeji HQ
                    totalCount: 15
                  - userId: cisuser2
                    userName: cis-user-1-2
                    status: Active
                    deleteFlag: false
                    areas:
                      - areaName: East Area
                      - areaName: West Area
                      - areaName: South Area
                    stores:
                      - storeName: Himeji HQ
                      - storeName: Tokyo HQ
                      - storeName: Shinagawa Office
                      - storeName: Saitama Factory
                    totalCount: 15
            example-2:
              value:
                totalCount: 0
                items: []
      headers: {}
    GetCisUsers:
      description: |-
        Response of Get /cis/users/{userId}
        If the number of results obtained is zero, status returns 200.
      content:
        application/json:
          schema:
            type: object
            properties:
              totalCount:
                type: number
                description: total count
              items:
                type: object
                required:
                  - userId
                  - userName
                  - status
                  - roles
                  - stores
                properties:
                  userId:
                    type: string
                    description: user ID(User ID of CIS user)
                  userName:
                    type: string
                    description: user name
                  status:
                    type: string
                    description: status
                    enum:
                      - Active
                      - Inactive
                  passwordChangeFlag:
                    type: boolean
                    description: password change flag(true is checked)
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        roleName:
                          type: string
                          description: role name
                      required:
                        - roleName
                  stores:
                    type: array
                    items:
                      type: object
                      properties:
                        storeName:
                          type: string
                          description: store name
                      required:
                        - storeName
            required:
              - totalCount
          examples:
            example-1:
              value:
                totalCount: 1
                items:
                  userId: cisuser1
                  userName: cis-user-1-1
                  status: Active
                  passwordChangeFlag: false
                  deleteFlag: false
                  roles:
                    - roleName: Manager
                  areas:
                    - areaName: East Area
                  stores:
                    - storeName: Himeji HQ
            example-2:
              value:
                totalCount: 0
  parameters:
    connect.sid:
      name: connect.sid
      in: cookie
      required: true
      schema:
        type: string
      description: Session ID (connect.sid=xxxxx)
    applicationId:
      name: applicationId
      in: query
      required: true
      schema:
        type: number
        minimum: 0
      description: Type of Application ID
    redirectUrl:
      name: redirectUrl
      in: query
      required: true
      schema:
        type: string
        minLength: 1
      description: URL to redirect after authentication
    code:
      name: code
      in: query
      required: false
      schema:
        type: string
        minLength: 1
      description: Authorization code (OAuth2 grant type = authorization_code)
    areaName:
      name: areaName
      in: query
      required: false
      schema:
        type: string
        minLength: 1
      description: Area name
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 10
        minimum: 0
      description: The number of items to return
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        default: 0
        minimum: 0
      description: The number of items to skip before starting to collect the result set
    storeName:
      name: storeName
      in: query
      required: false
      schema:
        type: string
        minLength: 1
      description: Store name
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        maxLength: 20
        pattern: '^[a-z0-9]+$'
        minLength: 1
      description: User ID
tags:
  - name: Area
  - name: CIS Role
  - name: CIS User
  - name: Store
  - name: User Auth
